---
all:
  hosts:
    jenkins-master-01:
      ansible_host: 51.250.16.54
    jenkins-agent-01:
      ansible_host: 51.250.106.123
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master-01:
        jenkins_agents:
          hosts:
              jenkins-agent-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: aledcherry
